name: "AWS secrets"
description: "Get AWS secrets and parameters"
inputs:
  secrets:
    description: "Secrets list"
    required: false
  parameters:
    description: "Parameters list"
    required: false
  prefix:
    description: "Parameters prefix"
    required: false
  namespace:
    description: "Omit keys namespace"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - id: format-secrets
      shell: bash
      run: SECRETS="${SECRETS_LIST//,/ }" echo "::set-output name=formatted::$SECRETS"
      env:
        SECRETS_LIST: ${{ inputs.secrets }}

    - shell: bash
      run: echo ${{steps.format-secrets.outputs.formatted}}
    - name: Read secrets from AWS Secrets Manager into environment variables
      if: ${{ inputs.secrets }} != ""
      uses: abhilash1in/aws-secrets-manager-action@v2.0.0
      with:
        secrets: ${{ inputs.secrets }}
        parse-json: true

    - name: Omit namespace in secrets
      if: ${{ inputs.secrets }} != "" && ${{ inputs.namespace }} != "true"
      shell: bash
      run: ${{ github.action_path }}/omit-secrets-namespace.sh
      env:
        SECRETS: ${{ inputs.secrets }}

    - name: Get parameter store values
      if: ${{ inputs.parameters }} != ""
      shell: bash
      run: ${{ github.action_path }}/ssm-params-to-env.sh
      env:
        PARAMETERS: ${{ inputs.parameters }}
        PREFIX: ${{ inputs.prefix }}
        NAMESPACE: ${{ inputs.namespace }}
