name: "AWS secrets"
description: "Get AWS secrets and parameters"
inputs:
  secrets:
    description: "Secrets list"
    required: false
  parameters:
    description: "Parameters list"
    required: false
    default: ""
  prefix:
    description: "Parameters prefix"
    required: false
  namespace:
    description: "Omit keys namespace"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - id: format-secrets
      shell: bash
      run: |
        SECRETS="${SECRETS_LIST//,/}"
        SECRETS="${SECRETS//'%'/'%25'}"
        SECRETS="${SECRETS//$'\n'/'%0A'}"
        SECRETS="${SECRETS//$'\r'/'%0D'}"
        echo "::set-output name=formatted::$SECRETS"
      env:
        SECRETS_LIST: ${{ inputs.secrets }}

    - shell: bash
      run: echo "${{steps.format-secrets.outputs.formatted}}"
    - name: Read secrets from AWS Secrets Manager into environment variables
      if: $${{steps.format-secrets.outputs.formatted}} != ""
      uses: abhilash1in/aws-secrets-manager-action@v2.0.0
      with:
        secrets: ${{steps.format-secrets.outputs.formatted}}
        parse-json: true

    - name: Omit namespace in secrets
      if: ${{steps.format-secrets.outputs.formatted}} != "" && ${{ inputs.namespace }} != "true"
      shell: bash
      run: $GITHUB_ACTION_PATH/omit-secrets-namespace.sh
      env:
        SECRETS: ${{steps.format-secrets.outputs.formatted}}

    - name: Get parameter store values
      if: ${{ inputs.parameters }} != ""
      shell: bash
      run: ${{ github.action_path }}/ssm-params-to-env.sh
      env:
        PARAMETERS: ${{ inputs.parameters }}
        PREFIX: ${{ inputs.prefix }}
        NAMESPACE: ${{ inputs.namespace }}
